apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  annotations:
    sidecar.jaegertracing.io/inject: "true"
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      release: prometheus
  template:
    metadata:
      labels:
        app: backend
        release: prometheus
    spec:
      containers:
      - name: backend
        image: noelsharker/dashboard_backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    app: backend
    release: prometheus
  ports:
    - name: backend
      port: 8081
      targetPort: 8080
  type: LoadBalancer