apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      release: prometheus
  template:
    metadata:
      labels:
        app: frontend
        release: prometheus
    spec:
      containers:
      - name: frontend
        image: noelsharker/dashboard_frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
    release: prometheus
spec:
  selector:
    app: frontend
    release: prometheus
  ports:
    - name: frontend
      port: 8082
      targetPort: 8080
  type: LoadBalancer